export const frontendConferenceData = [
  {
    name: "フロントエンドカンファレンス名古屋",
    nameEn: "Frontend Conference Nagoya",
    data: "2026-05-09",
    id: "fec-nagoya",
    url: "https://fec-nagoya-org.github.io/2026/",
    venue: "ウィンクあいち",
  },
  {
    name: "フロントエンドカンファレンス福岡",
    nameEn: "Frontend Conference Fukuoka",
    data: "2026-09-12",
    id: "fec-fukuoka",
    url: "https://frontend-conf.fukuoka.jp/2026/",
    venue: "九州産業大学 12号館",
  },
  {
    name: "フロントエンドカンファレンス東京",
    nameEn: "Frontend Conference Tokyo",
    data: "2026-12-05",
    id: "fec-tokyo",
    url: "https://fortee.jp/frontend-tokyo-2026",
    venue: "Abema Towers",
  },
  {
    name: "フロントエンドカンファレンス関西",
    nameEn: "Frontend Conference Kansai",
    data: "2026-10-12",
    id: "fec-kansai",
    url: "https://2026.frontend-conf.osaka.jp/",
    venue: "コングレスクエア グラングリーン大阪",
  },
] as const;

export const phpConferenceData = [
  {
    name: "PHPerKaigi 2026",
    nameEn: "PHPerKaigi 2026",
    data: "2026-03-20",
    id: "phperkaigi-2026",
    url: "https://phperkaigi.jp/2026/",
    venue: "中野セントラルパークカンファレンス",
  },
  {
    name: "PHPカンファレンス小田原2026",
    nameEn: "PHP Conference Odawara 2026",
    data: "2026-04-11",
    id: "phpcon-odawara-2026",
    url: "https://phpcon-odawara.jp/2026/",
    venue: "おだわら市民交流センター UMECO",
  },
  {
    name: "PHPカンファレンス香川2026",
    nameEn: "PHP Conference Kagawa 2026",
    data: "2026-05-09",
    id: "phpcon-kagawa-2026",
    url: "https://phpcon.kagawa.jp/2026/",
    venue: "玉藻公園内 披雲閣",
  },
  {
    name: "Laravel Live Japan",
    nameEn: "Laravel Live Japan",
    data: "2026-05-26",
    id: "laravel-live-japan-2026",
    url: "https://laravellive.jp/ja",
    venue: "立川ステージガーデン",
  },
  {
    name: "PHPカンファレンス2026",
    nameEn: "PHP Conference 2026",
    data: "2026-07-20",
    id: "phpcon-2026",
    url: "https://phpcon.php.gr.jp/2026/",
    venue: "大田区産業プラザPiO",
  },
  {
    name: "PHPカンファレンス愛媛2026",
    nameEn: "PHP Conference Ehime 2026",
    data: "2026-10-03",
    id: "phpcon-ehime-2026",
    url: "https://phpcon.ehime.jp/",
    venue: "愛媛大学 城北キャンパス",
  },
  {
    name: "PHPカンファレンス新潟2026",
    nameEn: "PHP Conference Niigata 2026",
    data: "2026-11-14",
    id: "phpcon-niigata-2026",
    url: "https://phpcon.niigata.jp/",
    venue: "朱鷺メッセ",
  },
] as const;
